### ISSUE TITLE
Why create multiple postgres services in docker-compose.yaml in module 2

### ISSUE THREAD

**Issue by kmajeed** [Tinker0425/de-zoomcamp-my-work#1]
Hi. Can you advise me why did you add multiple entries for postgress database in module 2 of your codes.

For example the `docker-compose.yaml` -> https://github.com/Tinker0425/de-zoomcamp-my-work/blob/master/module-02/video_3/docker-compose.yml

You created two services `kestra-metadata` service and `postgtres` both using image `postgres:17-alpine`
Then in your code for "Goal - View Empty Table in PgAdmin" you have used
```
pluginDefaults:
  - type: io.kestra.plugin.jdbc.postgresql
    values:
    url: jdbc:postgresql://kestra-metadata:5432/kestra
      username: kestra
      password: k3str4
```
Which I believe makes seconds postgtres service redundant.

Similarly in the following yaml for schedules and back filing 
https://github.com/Tinker0425/de-zoomcamp-my-work/blob/master/module-02/video_4/docker-compose.yml

you have declared two postgres services.
